import { StyleSheet } from 'react-native';

export const criarEstilos = (tema, fontSize, nomeTema) =>
  StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: tema.fundo,
      padding: 16
    },
    titulo: {
      fontSize: fontSize + 4,
      fontWeight: 'bold',
      color: tema.texto,
      textAlign: 'center',
      marginBottom: 16,
      marginTop: 10,
    },
    filtroContainer: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: '#f3f4f6',
      borderRadius: 8,
      paddingHorizontal: 12,
      marginBottom: 16,
      borderWidth: 1,
      borderColor: '#e5e7eb',
    },
    filtroIcon: {
      marginRight: 8,
    },
    filtroInput: {
      flex: 1,
      paddingVertical: 10,
      fontSize,
      color: 'black',
    },
    toggleButton: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: tema.botaoFundo,
      paddingVertical: 12,
      paddingHorizontal: 12,
      borderRadius: 8,
      marginBottom: 12,
      justifyContent: 'space-between',
    },
    toggleTexto: {
      flex: 1,
      color: '#fff',
      fontSize,
      fontWeight: '600',
      marginLeft: 8,
    },
    toggleLista: {
      backgroundColor: '#3b82f6',
      borderRadius: 8,
      marginBottom: 12,
      borderWidth: 1,
      borderColor: '#2563eb',
      overflow: 'hidden',
    },
    toggleItem: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingVertical: 12,
      paddingHorizontal: 14,
      borderBottomWidth: 1,
      borderBottomColor: '#2563eb',
      backgroundColor: '#3b82f6',
    },
    toggleItemSelecionado: {
      backgroundColor: '#1d4ed8',
      borderBottomColor: '#1d4ed8',
    },
    toggleItemTexto: {
      color: '#ffffff',
      fontSize,
      flex: 1,
    },
    toggleItemTextoSelecionado: {
      color: '#ffffff',
      fontWeight: '600',
    },
    sectionHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      backgroundColor: tema.fundoBotaoSecundario,
      paddingVertical: 10,
      paddingHorizontal: 12,
      borderRadius: 6,
      marginBottom: 12,
      marginTop: 12,
    },
    sectionTitle: {
      fontSize: fontSize + 1,
      fontWeight: '600',
      color: tema.texto,
    },
    sectionCount: {
      fontSize: fontSize - 2,
      color: tema.texto,
      backgroundColor: tema.botaoFundo,
      color: '#fff',
      paddingHorizontal: 8,
      paddingVertical: 2,
      borderRadius: 12,
      overflow: 'hidden',
    },
    item: {
      backgroundColor: nomeTema === 'claro' ? '#99ccff' : tema.botaoFundo,
      padding: 14,
      borderRadius: 10,
      marginBottom: 12,
      borderWidth: 1,
      borderColor: nomeTema === 'claro' ? '#66b3ff' : tema.botaoFundo,
    },
    itemHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginBottom: 10,
    },
    medicamentoInfo: {
      flexDirection: 'row',
      flex: 1,
      alignItems: 'center',
    },
    icone: {
      marginRight: 10,
    },
    textoContainer: {
      flex: 1,
    },
    textoMedicamento: {
      color: tema.botaoTexto,
      fontSize: fontSize + 1,
      fontWeight: '600',
      marginBottom: 2,
    },
    dose: {
      color: tema.botaoTexto,
      fontSize: fontSize - 2,
      opacity: 0.8,
    },
    statusContainer: {
      marginLeft: 10,
    },
    statusTomou: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 4,
    },
    statusNaoTomou: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 4,
    },
    statusTextoVerde: {
      color: '#22c55e',
      fontSize: fontSize - 2,
      fontWeight: '600',
    },
    statusTextoVermelho: {
      color: '#ef4444',
      fontSize: fontSize - 2,
      fontWeight: '600',
    },
    infoSecundaria: {
      flexDirection: 'row',
      alignItems: 'center',
      marginBottom: 8,
    },
    texto: {
      color: tema.botaoTexto,
      fontSize: fontSize - 1,
    },
    observacoesContainer: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      marginBottom: 10,
      paddingLeft: 0,
    },
    observacoes: {
      color: tema.botaoTexto,
      fontSize: fontSize - 2,
      flex: 1,
      fontStyle: 'italic',
    },
    botoes: {
      flexDirection: 'row',
      justifyContent: 'flex-end',
      gap: 8,
      marginTop: 10,
      paddingTop: 10,
      borderTopWidth: 1,
      borderTopColor: nomeTema === 'claro' ? '#66b3ff' : 'rgba(255,255,255,0.2)',
    },
    botaoEditar: {
      padding: 8,
      backgroundColor: tema.fundo,
      borderRadius: 6,
    },
    botaoExcluir: {
      padding: 8,
      backgroundColor: '#dc3545',
      borderRadius: 6,
    },
    vazio: {
      color: tema.texto,
      fontSize,
      textAlign: 'center',
      marginTop: 30,
      opacity: 0.6,
    },
    carregando: {
      flex: 1,
      justifyContent: 'center',
      alignItems: 'center',
    },
  });
